version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 0p3nw0rld
    ports:
      - "6033:3306"
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - network-mysql
      
networks:
  network-mysql:
    driver: bridge
    name: network-mysql
