version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 0p3w0lrd
      MYSQL_DATABASE: test
      MYSQL_USER: saynotodream
      MYSQL_PASSWORD: 0p3nw0rld
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    command: ["--user=root"]
    networks:
      - network-mysql
      
networks:
  network-mysql:
    driver: bridge
    name: network-mysql
