version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: my-mysql
    environment:
      MYSQL_ROOT_USER: saynotodream
      MYSQL_ROOT_PASSWORD: Saynotodream464606
      MYSQL_DATABASE: mysql
      MYSQL_USER: saynotodream
      MYSQL_PASSWORD: 464606
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - my_network

networks:
  my_network:
